version: '3.0'
services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - DEFAULT_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=sqs
      - LOCALSTACK_HOSTNAME=localhost
      - HOSTNAME_EXTERNAL=localhost
    ports:
      - '4566:4566'