cloud:
  aws:
    stack:
      auto: false
    region:
      static: us-east-1
    credentials:
      access-key: foo
      secret-key: bar
    end-point:
      uri: http://localhost:4566
    queue:
      name: order-queue